<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '{attribute} must be equal to "{compareValueOrAttribute}".' => 'Значение «{attribute}» должно быть равно «{compareValueOrAttribute}».',
    '{attribute} must be greater than "{compareValueOrAttribute}".' => 'Значение «{attribute}» должно быть больше значения «{compareValueOrAttribute}».',
    '{attribute} must be greater than or equal to "{compareValueOrAttribute}".' => 'Значение «{attribute}» должно быть больше или равно значения «{compareValueOrAttribute}».',
    '{attribute} must be less than "{compareValueOrAttribute}".' => 'Значение «{attribute}» должно быть меньше значения «{compareValueOrAttribute}».',
    '{attribute} must be less than or equal to "{compareValueOrAttribute}".' => 'Значение «{attribute}» должно быть меньше или равно значения «{compareValueOrAttribute}».',
    '{attribute} must not be equal to "{compareValueOrAttribute}".' => 'Значение «{attribute}» не должно быть равно «{compareValueOrAttribute}».',
    '(not set)' => '(не задано)',
    'Access denied' => 'Доступ запрещен',
    'An internal server error occurred.' => 'Возникла внутренняя ошибка сервера.',
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить этот элемент?',
    'Auth key' => 'Ключ авторизации',
    'Created at' => 'Дата создания',
    'Full name' => 'Полное имя',
    'Inspection stock' => 'Инспекция - склад',
    'ID' => 'ИД',
    'Incorrect username or password' => 'Неверно указано имя пользователя или пароль',
    'Login' => 'Авторизация',
    'Logout' => 'Выход',
    'Name' => 'Имя',
    'Password' => 'Пароль',
    'Please fill out the following fields' => 'Пожалуйста, заполните форму',
    'Role' => 'Роль',
    'Status' => 'Статус',
    'Surname' => 'Фамилия',
    'Updated at' => 'Дата последнего изменения',
    'User name' => 'Имя пользователя'
];
