<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '{attribute} must be equal to "{compareValueOrAttribute}".' => 'Значение «{attribute}» должно быть равно «{compareValueOrAttribute}».',
    '{attribute} must be greater than "{compareValueOrAttribute}".' => 'Значение «{attribute}» должно быть больше значения «{compareValueOrAttribute}».',
    '{attribute} must be greater than or equal to "{compareValueOrAttribute}".' => 'Значение «{attribute}» должно быть больше или равно значения «{compareValueOrAttribute}».',
    '{attribute} must be less than "{compareValueOrAttribute}".' => 'Значение «{attribute}» должно быть меньше значения «{compareValueOrAttribute}».',
    '{attribute} must be less than or equal to "{compareValueOrAttribute}".' => 'Значение «{attribute}» должно быть меньше или равно значения «{compareValueOrAttribute}».',
    '{attribute} must not be equal to "{compareValueOrAttribute}".' => 'Значение «{attribute}» не должно быть равно «{compareValueOrAttribute}».',
    '(not set)' => '(не задано)',
    'Access denied' => 'Доступ запрещен',
    'Active' => 'Активен',
    'Addition' => 'Добавление',
    'Add material' => 'Добавить материал',
    'Add user' => 'Добавить пользователя',
    'An internal server error occurred.' => 'Возникла внутренняя ошибка сервера.',
    'Are you sure you want to block this user' => 'Вы уверены, что хотите заблокировать данного пользователя',
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить этот элемент?',
    'Auth key' => 'Ключ авторизации',
    'Block' => 'Заблокировать',
    'Changed' => 'Изменено',
    'Created at' => 'Дата создания',
    'Created by' => 'Кто добавил',
    'Delete' => 'Удалить',
    'Delete material' => 'Удалить материал',
    'Disabled' => 'Блокирован',
    'Edit material card' => 'Редактировать карту материала',
    'Fill only if you want to change old one' => 'Заполняется только в случае изменения старого пароля',
    'Full name' => 'Полное имя',
    'Group' => 'Группа',
    'Inspection stock' => 'Инспекция - склад',
    'ID' => 'ИД',
    'Impossible to delete this user' => 'Невозможно заблокировать пользователя',
    'Impossible to restore this user' => 'Невозможно разблокировать пользователя',
    'Incorrect username or password' => 'Неверно указано имя пользователя или пароль',
    'Kg' => 'Кг',
    'Last edition' => 'Последнее изменение',
    'Latin letters and digits' => 'Буквы латинского алфавита и цифры',
    'Latin letters, digits, special symbols' => 'Буквы латинского алфавита, цифры, спецсимволы',
    'login' => 'Логин',
    'Login' => 'Авторизация',
    'Logout' => 'Выход',
    'Main' => 'Главная',
    'Materials' => 'Материалы',
    'Material name' => 'Описание материала',
    'Meters' => 'м',
    'Name' => 'Имя',
    'Max qty' => 'Максимальное количество',
    'Min qty' => 'Критически низкое количество',
    'New password' => 'Новый пароль',
    'Not set' => 'Не задано',
    'Pairs' => 'Пар',
    'Password' => 'Пароль',
    'Pcs' => 'Шт',
    'Please fill out the following fields' => 'Пожалуйста, заполните форму',
    'Photo' => 'Фото',
    'Position' => 'Должность',
    'Qty' => 'Текущее количесткво',
    'Ref' => 'Номер САП',
    'Restore' => 'Разблокировать',
    'Role' => 'Роль',
    'Russian letters only' => 'Только русские буквы',
    'Save' => 'Сохранить',
    'Status' => 'Статус',
    'Surname' => 'Фамилия',
    'Type' => 'Тип',
    'Unit' => 'Единица измерения',
    'Update' => 'Редактировать',
    'Updating' => 'Редактирование',
    'Updated at' => 'Дата последнего изменения',
    'Updated by' => 'Кто отредактировал',
    'Update user: {name}' => 'Редактирование: {name}',
    'Users' => 'Пользователи',
    'User with role {role} will be restored' => 'Пользователь будет восстановлен с ролью {role}',
    'User name' => 'Имя пользователя'
];
